[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "martech-use-case"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "dagster",
    "dagster-webserver",
    "dagster-dex[dex]",
    "exmergo-dex-core[duckdb]==1.12.3",
    "pandas",
    "duckdb",
]

[tool.setuptools]
packages = ["martech", "martech.assets"]
